# Generated by Django 3.2.7 on 2021-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Technology', 'Technology')], default='', max_length=50)),
            ],
        ),
    ]
