# Generated by Django 3.2.7 on 2021-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploadimg')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
