# Generated by Django 3.2.7 on 2021-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('IT', 'IT'), ('Sports', 'Sports'), ('National', 'National')], default='', max_length=50),
        ),
    ]
